# Generated by Django 2.0.7 on 2018-07-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
